version: "3"

services:
  fcgi:
    build: ../server_5
  nginx:
    build: ./nginx
    volumes:
      - ${PWD}/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:8080"
    depends_on:
      - fcgi