state_sort : state_sort.o
	gcc state_sort.o -o ../build/Quest_1
	rm -f *.o
state_sort.o : state_sort.c
	gcc -c -Wall -Werror -Wextra state_sort.c
state_search : state_search.o
	gcc state_search.o -o ../build/Quest_2
	rm -f *.o
state_search.o : state_search.c
	gcc -c -Wall -Werror -Wextra state_search.c
clear_state : clear_state.o
	gcc clear_state.o -o ../build/Quest_3
	rm -f *.o
clear_state.o : clear_state.c
	gcc -c -Wall -Werror -Wextra clear_state.c